package com.yupi.yuaiagent.tools;

import cn.hutool.core.io.FileUtil;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import com.yupi.yuaiagent.constant.FileConstant;
import com.yupi.yuaiagent.tools.pdf.PdfTemplateData;
import com.yupi.yuaiagent.tools.pdf.PdfTemplateRenderer;
import com.yupi.yuaiagent.tools.pdf.PdfTemplateType;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * PDF generation tool backed by HTML/CSS templates.
 */
public class PDFGenerationTool {

    private static final List<String> FONT_CANDIDATES = List.of(
            "C:/Windows/Fonts/msyh.ttf",
            "C:/Windows/Fonts/simhei.ttf",
            "C:/Windows/Fonts/simkai.ttf",
            "C:/Windows/Fonts/simsun.ttf"
    );

    private static final String DEFAULT_THEME_COLOR = "#ff4d6d";

    private final PdfTemplateRenderer pdfTemplateRenderer = new PdfTemplateRenderer();

    @Tool(
            description = "Generate a styled PDF using a default poster template. " +
                    "Use this for quick visual PDFs when only file name and text content are available.",
            returnDirect = false
    )
    public String generatePDF(
            @ToolParam(description = "Name of the file to save the generated PDF") String fileName,
            @ToolParam(description = "Main content to be included in the PDF") String content) {
        PdfTemplateData templateData = new PdfTemplateData(
                ensurePdfExtension(fileName),
                PdfTemplateType.POSTER,
                "AI Visual PDF",
                "Generated by Yu AI Agent",
                content,
                null,
                DEFAULT_THEME_COLOR
        );
        return renderTemplatePdf(templateData);
    }

    @Tool(
            description = "Generate a visually rich PDF from structured content. " +
                    "Supported templates: poster, report, card. " +
                    "Pass title, subtitle, content, optional image URL or local image path, and a theme color like #ff4d6d.",
            returnDirect = false
    )
    public String generateStyledPdf(
            @ToolParam(description = "Name of the file to save the generated PDF") String fileName,
            @ToolParam(description = "Template type: poster, report, or card") String template,
            @ToolParam(description = "Main title shown prominently in the PDF") String title,
            @ToolParam(description = "Secondary title or supporting line") String subtitle,
            @ToolParam(description = "Main body content. You can use multiple paragraphs separated by blank lines") String content,
            @ToolParam(description = "Optional image URL or local image path. Leave blank if no image is needed") String imageUrl,
            @ToolParam(description = "Theme color in hex format such as #ff4d6d") String themeColor
    ) {
        PdfTemplateData templateData = new PdfTemplateData(
                ensurePdfExtension(fileName),
                PdfTemplateType.from(template),
                safeText(title, "AI Visual PDF"),
                safeText(subtitle, "Generated by Yu AI Agent"),
                safeText(content, "No content provided."),
                imageUrl,
                normalizeThemeColor(themeColor)
        );
        return renderTemplatePdf(templateData);
    }

    private String renderTemplatePdf(PdfTemplateData templateData) {
        String fileDir = FileConstant.FILE_SAVE_DIR + "/pdf";
        String filePath = fileDir + "/" + templateData.fileName();
        try {
            FileUtil.mkdir(fileDir);
            String html = pdfTemplateRenderer.render(
                    templateData.withResolvedImageUrl(resolveImageUrl(templateData.imageUrl()))
            );
            try (OutputStream outputStream = new FileOutputStream(filePath)) {
                PdfRendererBuilder builder = new PdfRendererBuilder();
                builder.useFastMode();
                builder.withHtmlContent(html, new File(fileDir).toURI().toString());
                registerFont(builder);
                builder.toStream(outputStream);
                builder.run();
            }
            String previewUrl = buildPreviewUrl(templateData.fileName());
            return """
                    PDF已生成
                    文件路径: %s
                    访问地址: %s
                    PDF_URL::%s
                    """.formatted(filePath, previewUrl, previewUrl);
        } catch (Exception e) {
            return "Error generating PDF: " + e.getMessage();
        }
    }

    private String buildPreviewUrl(String fileName) {
        return "/api/files/pdf/" + URLEncoder.encode(fileName, StandardCharsets.UTF_8)
                .replace("+", "%20");
    }

    private void registerFont(PdfRendererBuilder builder) throws IOException {
        for (String fontPath : FONT_CANDIDATES) {
            Path path = Path.of(fontPath);
            if (Files.exists(path)) {
                builder.useFont(path.toFile(), "CustomPdfFont");
                return;
            }
        }
    }

    private String resolveImageUrl(String imageUrl) {
        if (imageUrl == null || imageUrl.isBlank()) {
            return null;
        }
        String trimmed = imageUrl.trim();
        if (trimmed.startsWith("http://") || trimmed.startsWith("https://") || trimmed.startsWith("data:")) {
            return trimmed;
        }
        Path localPath = Path.of(trimmed);
        if (Files.exists(localPath)) {
            return localPath.toAbsolutePath().toUri().toString();
        }
        return trimmed;
    }

    private String ensurePdfExtension(String fileName) {
        String normalized = safeText(fileName, "generated.pdf").trim();
        if (normalized.toLowerCase().endsWith(".pdf")) {
            return normalized;
        }
        return normalized + ".pdf";
    }

    private String normalizeThemeColor(String themeColor) {
        String normalized = safeText(themeColor, DEFAULT_THEME_COLOR).trim();
        if (normalized.matches("^#[0-9a-fA-F]{6}$")) {
            return normalized;
        }
        return DEFAULT_THEME_COLOR;
    }

    private String safeText(String text, String fallback) {
        if (text == null || text.isBlank()) {
            return fallback;
        }
        return text.trim();
    }
}
